inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Naming/FileName:
  Exclude:
    - 'lib/ruby-limiter.rb'
